spring:
  application:
    name: ekke-enco-prosamp-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/prosampdb
    username: prosamp
    password: prosamp
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
  address: localhost
