spring:
  application:
    name: ekke-enco-prosamp-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/prosampdb
    username: prosamp
    password: prosamp
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5                   # Minimum number of idle connections maintained in the pool
      maximum-pool-size: 20             # Maximum number of connections in the pool
      idle-timeout: 60000               # 1 minute - how long a connection can remain idle before being closed
      max-lifetime: 1800000             # 30 minutes - maximum lifetime of a connection in the pool
      connection-timeout: 30000         # 30 seconds - maximum time to wait for a connection from the pool
      validation-timeout: 5000          # 5 seconds - time to wait for connection validation
      leak-detection-threshold: 20000   # 20 seconds - log a warning if a connection is open longer than this
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/encotech
          jwk-set-uri: http://localhost:8082/realms/encotech/protocol/openid-connect/certs

server:
  port: 8081
  address: localhost


